# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
workflows:
  deploy-test:
    jobs:
      - test
jobs:
  test:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout
      - run:
         name: install dependencies
         command: npm i
      - run: node --version
          
